### ISSUE TITLE
"double spend" vs "double-spend"

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#456]
This is hyphenated inconsistently. I suggest always hyphenating it.

(An alternative is to hyphenate it when used adjectivally, and not when used as a noun phrase, but that's fiddly, and is not what is currently done.)

**Comment by aantonop** [comment]
I believe this was fixed by the O'Reilly editors in the first print. I can only find it in the form "double spending" in the glossary (and also in Satoshi's whitepaper). Neither are hyphenated, but I think that's ok in that case.

**Comment by rrthomas** [comment]
Looking at current git, "double-spend" still occurs 20 times (if I understood you, you're saying you're happy to leave it always unhyphenated, which is fine by me).

**Comment by aantonop** [comment]
It only occurs hyphenated now
